#!/usr/bin/env bash
: '
| Filename    : ex
| Description : Site Deployment and Building.
| Author      : Pushpendre Rastogi
| Created     : Fri Mar 15 22:21:15 2019 (-0400)
| Last-Updated: .
|           By: .
|     Update #: 0
'
FNC=${1-expt}
PFX=${2-echo}
ARGS="${@:2}"
INS="sudo port install"
export PATH=/Users/prastogi/Library/Python/3.5/bin:"${PATH}"
setup () {
  $INS python35 py35-pip fswatch libmagic
  sudo chown -R prastogi:admin /Users/prastogi/Library/Python/3.5
  pip-3.5 install pyxl4 biblib --user
  rclone copy dbx:Bibliography_all.bib ../../
  curl -L https://raw.githubusercontent.com/dropbox/pyxl/master/emacs/pyxl-mode.el >  ~/cfg/emacs.d/mymodes/pyxl-mode.el
  ## Do these steps to get the dependencies
  # pip-3.5 uninstall biblib
  # pushd $PWD
  # cd /tmp
  # git clone https://github.com/aclements/biblib.git --depth 1
  # pushd $PWD
  # cd biblib/
  # python3.5 setup.py install

}
build () {
  python3.5 index.py > index.html
  echo 'Compiled index.html'
  while : ; do
    python3.5 $(fswatch -1 index.py) > index.html
    echo 'Compiled index.html'
  done
}
push () {
  # Push is different from deploy.
  IFS= $PFX read -s  -p Password: pwd
  echo
  $PFX git push $ARGS https://pushpendre:"$pwd"@github.com/pushpendre/pushpendre.github.io.git
}
serve () {
  python -m http.server &
}
deploy () {
  set -e
  $PFX cp -r *.html mvlsa res ../
  $PFX cd ../
  $PFX git add --all
  $PFX git commit -m "Update"
  $PFX git push origin master
  $PFX cd -
  set +ex
}
trbsht () {
  open https://github.com/pushpendre/pushpendre.github.io/settings
}
show () {
  type $1
}
$FNC $ARGS
